export type Difficulty = "Beginner" | "Intermediate" | "Advanced"

export type Category = "Strength" | "Cardio" | "Flexibility" | "HIIT"

export interface Exercise {
  id: string
  name: string
  category: Category
  difficulty: Difficulty
  duration: number
  muscles: string[]
  description: string
  instructions: string[]
  calories: number
}

export const exercises: Exercise[] = [
  {
    id: "push-up",
    name: "Push-Up",
    category: "Strength",
    difficulty: "Beginner",
    duration: 10,
    muscles: ["Chest", "Triceps", "Shoulders"],
    description: "A classic bodyweight exercise that builds upper body strength and core stability.",
    instructions: [
      "Start in a high plank position with hands shoulder-width apart",
      "Keep your body in a straight line from head to heels",
      "Lower your chest to the floor by bending your elbows",
      "Push back up to the starting position",
      "Complete 3 sets of 10–15 reps",
    ],
    calories: 60,
  },
  {
    id: "squat",
    name: "Squat",
    category: "Strength",
    difficulty: "Beginner",
    duration: 10,
    muscles: ["Quadriceps", "Hamstrings", "Glutes"],
    description: "The king of lower body exercises. Builds leg strength and improves mobility.",
    instructions: [
      "Stand with feet shoulder-width apart, toes slightly turned out",
      "Keeping your chest up, bend your knees and push your hips back",
      "Lower until your thighs are parallel to the ground",
      "Drive through your heels to return to standing",
      "Complete 3 sets of 12–15 reps",
    ],
    calories: 70,
  },
  {
    id: "plank",
    name: "Plank",
    category: "Strength",
    difficulty: "Beginner",
    duration: 5,
    muscles: ["Core", "Shoulders", "Back"],
    description: "An isometric core exercise that builds endurance in the abs, back, and stabilizers.",
    instructions: [
      "Start in a forearm plank position with elbows under shoulders",
      "Keep your body in a straight line from head to heels",
      "Engage your core and squeeze your glutes",
      "Hold for 30–60 seconds",
      "Complete 3 sets",
    ],
    calories: 30,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "Strength",
    difficulty: "Intermediate",
    duration: 15,
    muscles: ["Hamstrings", "Glutes", "Back", "Core"],
    description: "A fundamental compound movement for building total body strength and power.",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot",
      "Hinge at the hips and grip the bar just outside your legs",
      "Keep your back flat and chest up as you drive through your heels",
      "Stand tall at the top, squeezing your glutes",
      "Lower the bar with control back to the floor",
    ],
    calories: 120,
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    category: "Strength",
    difficulty: "Intermediate",
    duration: 10,
    muscles: ["Lats", "Biceps", "Rhomboids"],
    description: "A challenging upper body pulling exercise that builds back and arm strength.",
    instructions: [
      "Hang from a bar with an overhand grip, hands shoulder-width apart",
      "Engage your core and squeeze your shoulder blades",
      "Pull your chest up towards the bar",
      "Lower yourself back down with control",
      "Complete 3 sets of 5–10 reps",
    ],
    calories: 80,
  },
  {
    id: "running",
    name: "Running",
    category: "Cardio",
    difficulty: "Beginner",
    duration: 30,
    muscles: ["Legs", "Core", "Cardiovascular System"],
    description: "The most accessible cardio exercise. Improves cardiovascular fitness and burns calories.",
    instructions: [
      "Start with a 5-minute warm-up walk",
      "Run at a conversational pace — you should be able to speak short sentences",
      "Maintain good posture: upright torso, relaxed arms",
      "Land mid-foot to reduce impact",
      "Cool down with a 5-minute walk and light stretching",
    ],
    calories: 300,
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    category: "Cardio",
    difficulty: "Beginner",
    duration: 15,
    muscles: ["Calves", "Shoulders", "Core"],
    description: "A fun, high-intensity cardio exercise that improves coordination and agility.",
    instructions: [
      "Hold handles at hip height with elbows close to your sides",
      "Start with basic two-foot jumps, landing softly on the balls of your feet",
      "Keep jumps small — just enough to clear the rope",
      "Rotate the rope with your wrists, not your arms",
      "Aim for 3 sets of 60 seconds",
    ],
    calories: 180,
  },
  {
    id: "cycling",
    name: "Cycling",
    category: "Cardio",
    difficulty: "Beginner",
    duration: 30,
    muscles: ["Quadriceps", "Hamstrings", "Calves", "Core"],
    description: "Low-impact cardio that's gentle on the joints while building leg endurance.",
    instructions: [
      "Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke",
      "Start at a moderate resistance and comfortable cadence",
      "Maintain an upright or slightly forward posture",
      "Breathe rhythmically throughout",
      "Cool down with 5 minutes of easy pedaling",
    ],
    calories: 250,
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "HIIT",
    difficulty: "Intermediate",
    duration: 10,
    muscles: ["Full Body", "Core", "Cardiovascular System"],
    description: "A full-body explosive movement combining a squat, plank, and jump for maximum intensity.",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Drop into a squat and place your hands on the floor",
      "Jump your feet back into a plank position",
      "Do a push-up (optional but recommended)",
      "Jump your feet back toward your hands, then explode upward with arms overhead",
    ],
    calories: 150,
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    category: "HIIT",
    difficulty: "Intermediate",
    duration: 10,
    muscles: ["Core", "Shoulders", "Hip Flexors", "Legs"],
    description: "A dynamic plank variation that spikes your heart rate and engages the entire body.",
    instructions: [
      "Start in a high plank with wrists directly under shoulders",
      "Drive one knee toward your chest, then quickly switch legs",
      "Keep your hips level and core tight throughout",
      "Alternate legs as fast as you can while maintaining form",
      "Complete 3 sets of 20–30 seconds",
    ],
    calories: 120,
  },
  {
    id: "box-jumps",
    name: "Box Jumps",
    category: "HIIT",
    difficulty: "Advanced",
    duration: 15,
    muscles: ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    description: "An explosive lower body plyometric exercise that builds power and athleticism.",
    instructions: [
      "Stand facing a sturdy box or platform (start with 12–18 inches)",
      "Lower into a quarter squat and swing your arms back",
      "Explosively jump onto the box, landing softly with both feet",
      "Fully extend your hips at the top",
      "Step back down carefully and repeat for 3 sets of 8–10 reps",
    ],
    calories: 140,
  },
  {
    id: "yoga-flow",
    name: "Sun Salutation",
    category: "Flexibility",
    difficulty: "Beginner",
    duration: 20,
    muscles: ["Full Body", "Spine", "Hip Flexors"],
    description: "A flowing yoga sequence that improves flexibility, strength, and mindfulness.",
    instructions: [
      "Begin in Mountain Pose at the top of your mat",
      "Inhale and sweep arms overhead into Upward Salute",
      "Exhale and fold forward into Standing Forward Fold",
      "Step or jump back to a high plank, lower to Chaturanga",
      "Inhale into Upward Dog, exhale into Downward Dog — hold 5 breaths",
    ],
    calories: 80,
  },
  {
    id: "hip-flexor-stretch",
    name: "Hip Flexor Stretch",
    category: "Flexibility",
    difficulty: "Beginner",
    duration: 10,
    muscles: ["Hip Flexors", "Quadriceps", "Groin"],
    description: "Targeted stretch to release tight hip flexors, common from prolonged sitting.",
    instructions: [
      "Kneel on one knee with the other foot in front (lunge position)",
      "Shift your hips forward gently until you feel a stretch in the front of the rear hip",
      "Keep your torso upright and core engaged",
      "Hold for 30 seconds, then switch sides",
      "Repeat 2–3 times per side",
    ],
    calories: 20,
  },
  {
    id: "foam-rolling",
    name: "Foam Rolling",
    category: "Flexibility",
    difficulty: "Beginner",
    duration: 15,
    muscles: ["IT Band", "Quads", "Hamstrings", "Back"],
    description: "Self-myofascial release that reduces muscle soreness and improves mobility.",
    instructions: [
      "Position the foam roller under the target muscle group",
      "Use your body weight to apply pressure to the roller",
      "Roll slowly, about 1 inch per second",
      "Pause on tender spots for 5–10 seconds",
      "Spend 60–90 seconds per muscle group",
    ],
    calories: 15,
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "Strength",
    difficulty: "Intermediate",
    duration: 15,
    muscles: ["Shoulders", "Triceps", "Upper Back"],
    description: "A compound pressing movement that builds shoulder strength and stability.",
    instructions: [
      "Stand with feet shoulder-width apart, bar at shoulder height",
      "Grip the bar just outside shoulder width",
      "Press the bar overhead, finishing with arms fully extended",
      "Lower back to shoulder height with control",
      "Complete 3 sets of 8–10 reps",
    ],
    calories: 100,
  },
  {
    id: "tabata",
    name: "Tabata Intervals",
    category: "HIIT",
    difficulty: "Advanced",
    duration: 20,
    muscles: ["Full Body", "Cardiovascular System"],
    description: "8 rounds of 20 seconds max effort followed by 10 seconds rest. Brutal and effective.",
    instructions: [
      "Choose an exercise: sprints, burpees, or cycling",
      "Work at 100% effort for 20 seconds",
      "Rest for exactly 10 seconds",
      "Repeat for 8 rounds (4 minutes total)",
      "Take 1 minute rest between Tabata sets",
    ],
    calories: 200,
  },
]

export const categories: Category[] = ["Strength", "Cardio", "HIIT", "Flexibility"]

export const categoryColors: Record<Category, string> = {
  Strength: "bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-200 dark:border-blue-800",
  Cardio: "bg-green-500/10 text-green-700 dark:text-green-400 border-green-200 dark:border-green-800",
  HIIT: "bg-red-500/10 text-red-700 dark:text-red-400 border-red-200 dark:border-red-800",
  Flexibility: "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-800",
}

export const difficultyColors: Record<Difficulty, string> = {
  Beginner: "text-green-600 dark:text-green-400",
  Intermediate: "text-amber-600 dark:text-amber-400",
  Advanced: "text-red-600 dark:text-red-400",
}
